QaAutomationOIDCRoleArn: ''
QaAutomationUserAccessKeyId: ''
QaAutomationUserSecretAccessKey: ''

QaAutomationRoles:
  defaultAlias: roleqa
  roledev:
    roleArn: ''
    sessionName: ''
  roleqa:
    roleArn: ''
    sessionName: ''

DEV:
  apiTokens:
    value: ''
    url: ''
    clientId: ''
    clientSecret: ''
    uiURL: ''
    oauth2ApiKey: ''
    oauth2ClientId: ''
    oauth2ClientSecret: ''
    essUsername: ''
    essPassword: ''
    javaoxxooldurl: ''
    callTextUrl: ''
    callTextApiKey: ''
    payApiBaseUri: ''
  dbTokens:
    rac: ''
    ent:
      host: ''
      port: ''
      serviceName: ''
      username: ''
      password: ''
    prc: ''
    config: ''
    upbpay: ''
    van: ''
    webleads: ''
    ods: ''
    custapproval: ''
    csm: ''
    promo: ''
    workday: ''
  awsTokens:
    accessKey: ''
    secretKey: ''
    sessionToken: ''

DEV2:
  apiTokens:
    value: ''
    url: ''
    clientId: ''
    clientSecret: ''
    uiURL: ''
    oauth2ApiKey: ''
    oauth2ClientId: ''
    oauth2ClientSecret: ''
    essUsername: ''
    essPassword: ''
    javaoxxooldurl: ''
    callTextUrl: ''
    callTextApiKey: ''
    payApiBaseUri: ''
  dbTokens:
    rac: ''
    ent: ''
    prc: ''
    config: ''
    upbpay: ''
    van: ''
    webleads: ''
    ods: ''
    custapproval: ''
    csm: ''
    promo: ''
  awsTokens:
    accessKey: ''
    secretKey: ''
    sessionToken: ''

DEV3:
  apiTokens:
    value: ''
    url: ''
    clientId: ''
    clientSecret: ''
    uiURL: ''
    oauth2ApiKey: ''
    oauth2ClientId: ''
    oauth2ClientSecret: ''
    essUsername: ''
    essPassword: ''
    javaoxxooldurl: ''
    callTextUrl: ''
    callTextApiKey: ''
    payApiBaseUri: ''
  dbTokens:
    rac: ''
    ent: ''
    prc: ''
    config: ''
    upbpay: ''
    van: ''
    webleads: ''
    ods: ''
    custapproval: ''
    csm: ''
    promo: ''

QA:
  apiTokens:
    value: ''
    url: ''
    clientId: ''
    clientSecret: ''
    uiURL: ''
    oauth2ApiKey: ''
    oauth2ClientId: ''
    oauth2ClientSecret: ''
    essUsername: ''
    essPassword: ''
    javaoxxooldurl: ''
    callTextUrl: ''
    callTextApiKey: ''
    payApiBaseUri: ''
    sfApiBaseUri: ''
  dbTokens:
    rac: ''
    ent:
      host: ''
      port: ''
      serviceName: ''
      username: ''
      password: ''
    prc: ''
    config: ''
    upbpay: ''
    van: ''
    webleads: ''
    ods: ''
    custapproval: ''
    csm: ''
    promo: ''

QA2:
  apiTokens:
    value: ''
    url: ''
    clientId: ''
    clientSecret: ''
    uiURL: ''
    oauth2ApiKey: ''
    oauth2ClientId: ''
    oauth2ClientSecret: ''
    essUsername: ''
    essPassword: ''
    javaoxxooldurl: ''
    callTextUrl: ''
    callTextApiKey: ''
    payApiBaseUri: ''
  dbTokens:
    rac: ''
    ent: ''
    prc: ''
    config: ''
    upbpay: ''
    van: ''
    webleads: ''
    ods: ''
    custapproval: ''
    csm: ''
    promo: ''

QA3:
  apiTokens:
    value: ''
    url: ''
    clientId: ''
    clientSecret: ''
    uiURL: ''
    oauth2ApiKey: ''
    oauth2ClientId: ''
    oauth2ClientSecret: ''
    essUsername: ''
    essPassword: ''
    javaoxxooldurl: ''
    callTextUrl: ''
    callTextApiKey: ''
    payApiBaseUri: ''
  dbTokens:
    rac: ''
    ent: ''
    prc: ''
    config: ''
    upbpay: ''
    van: ''
    webleads: ''
    ods: ''
    custapproval: ''
    csm: ''
    promo: ''

UAT:
  apiTokens:
    value: ''
    url: ''
    clientId: ''
    clientSecret: ''
    uiURL: ''
    oauth2ApiKey: ''
    oauth2ClientId: ''
    oauth2ClientSecret: ''
    essUsername: ''
    essPassword: ''
    javaoxxooldurl: ''
    callTextUrl: ''
    callTextApiKey: ''
    payApiBaseUri: ''
  dbTokens:
    rac: ''
    ent: ''
    prc: ''
    config: ''
    upbpay: ''
    van: ''
    webleads: ''
    ods: ''
    custapproval: ''
    csm: ''
    promo: ''

UAT2:
  apiTokens:
    value: ''
    url: ''
    clientId: ''
    clientSecret: ''
    uiURL: ''
    oauth2ApiKey: ''
    oauth2ClientId: ''
    oauth2ClientSecret: ''
    essUsername: ''
    essPassword: ''
    javaoxxooldurl: ''
    callTextUrl: ''
    callTextApiKey: ''
    payApiBaseUri: ''
  dbTokens:
    rac: ''
    ent: ''
    prc: ''
    config: ''
    upbpay: ''
    van: ''
    webleads: ''
    ods: ''
    custapproval: ''
    csm: ''
    promo: ''

TRAINING:
  apiTokens:
    value: ''
    url: ''
    clientId: ''
    clientSecret: ''
    uiURL: ''
    oauth2ApiKey: ''
    oauth2ClientId: ''
    oauth2ClientSecret: ''
    essUsername: ''
    essPassword: ''
    javaoxxooldurl: ''
    callTextUrl: ''
    callTextApiKey: ''
    payApiBaseUri: ''
  dbTokens:
    rac: ''
    ent: ''
    prc: ''
    config: ''
    upbpay: ''
    van: ''
    webleads: ''
    ods: ''
    custapproval: ''
    csm: ''
    promo: ''

TRAINING2:
  apiTokens:
    value: ''
    url: ''
    clientId: ''
    clientSecret: ''
    uiURL: ''
    oauth2ApiKey: ''
    oauth2ClientId: ''
    oauth2ClientSecret: ''
    essUsername: ''
    essPassword: ''
    javaoxxooldurl: ''
    callTextUrl: ''
    callTextApiKey: ''
    payApiBaseUri: ''
  dbTokens:
    rac: ''
    ent: ''
    prc: ''
    config: ''
    upbpay: ''
    van: ''
    webleads: ''
    ods: ''
    custapproval: ''
    csm: ''
    promo: ''

PERF:
  apiTokens:
    value: ''
    url: ''
    clientId: ''
    clientSecret: ''
    uiURL: ''
    oauth2ApiKey: ''
    oauth2ClientId: ''
    oauth2ClientSecret: ''
    essUsername: ''
    essPassword: ''
    javaoxxooldurl: ''
    callTextUrl: ''
    callTextApiKey: ''
    payApiBaseUri: ''
  dbTokens:
    rac: ''
    ent: ''
    prc: ''
    config: ''
    upbpay: ''
    van: ''
    webleads: ''
    ods: ''
    custapproval: ''
    csm: ''
    promo: ''

STAGE:
  apiTokens:
    value: ''
    url: ''
    clientId: ''
    clientSecret: ''
    uiURL: ''
    oauth2ApiKey: ''
    oauth2ClientId: ''
    oauth2ClientSecret: ''
    essUsername: ''
    essPassword: ''
    javaoxxooldurl: ''
    callTextUrl: ''
    callTextApiKey: ''
    payApiBaseUri: ''
  dbTokens:
    rac: ''
    ent: ''
    prc: ''
    config: ''
    upbpay: ''
    van: ''
    webleads: ''
    ods: ''
    custapproval: ''
    csm: ''
    promo: ''
